POST http://localhost:5001/api/salads HTTP/1.1

{
    "name": "Olivie",
    "weight": 1.0,
    "ingredients": ["potatoes", "sausage", "pea", "eggs", "cucumbers"],
    "sauce": "mayonnaise",
    "dietType": "none",
    "spicy": false,
    "expired_date": "2024-06-10"
}